wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/src/pretraining/wav2vec2_pretraining.py
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1664863979.689095
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.10.4
      5: 0.13.3
      6: 4.22.1
      8:
      - 5
