modality: 'vision'
device: 'cuda'
model:
  encoder_checkpoint: 'microsoft/beit-base-patch16-224-pt22k'
  embed_dim: 768
  average_top_k_layers: 6
  head_layers: 2
  num_classes: 1000
  normalize_targets: false
  ema_decay: 0.9998
  ema_end_decay: 0.9999
  ema_anneal_end_step: 300000
dataset:
  path:
    train: 'vision/dummy_data'
    test:  'vision/dummy_data'
  input_size: 224
  interpolation: 'bicubic'
  patch_size: 16
  num_patches: 14
  num_mask_patches: 120
  max_mask_patches_per_block: 196
  min_mask_patches_per_block: 16
  imagenet_default_mean_and_std: false
train:
  num_epochs: 800
  batch_size: 16
  shuffle: true
  save_ckpt_freq: 20
  checkpoints_dir: 'vision/checkpoints/beit-pretrain'
  log_dir: 'vision/logs/beit-pretrain'
criterion:
  loss_beta: 2
optimizer:
  lr: 2e-3




